version: "3.8"
services:
  mongodb-adam:
    image:  'mongo'
    volumes:
      - data:/data1/db
    env_file:  
      - ./backend/env/mongo.env
     
  backend:
    build: ./backend
    ports:
      - "81:81"
    volumes: 
      - logs:/apps/logs  
      - ./backend:/app
      - /app/node_modules
    env_file:  
      - ./backend/env/backend.env
    depends_on:
      - mongodb-adam 



  frontend:
    build: ./frontend
    ports:
      - '3002:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend


volumes:
  data:
  logs: